const ClarityInTheMoment_AddressingConflict = [
  {
      id: '1',
      data: {
          "Figuring Things Out": `${mainChar} is rationalizing the situation `,
          "Figuring Things Out": `${mainChar} has not figured it out yet`,
          "Conflict": `${mainChar} is not making an effort to strengthen their relationship`,
          "Harmony": `${mainChar} is making an effort to strengthen their relationship`,
          "Respect and Authority": `${mainChar} is losing respect`,
          "Losing Security, Stability, Trust": `${mainChar} does not feel better`,
          "Figuring Things Out": `${otherChar} is rationalizing the situation `,
          "Conflict": `${otherChar} is not making an effort to strengthen their relationship`,
          "Conflict": `${otherChar} criticized and complained`,
          "Conflict": `${otherChar} is being hurtful and disrespectful`,
          "Communication": `${otherChar} did not communicate well`,
          "Respect and Authority": `${otherChar} is losing respect`,
          "Expectations And Ability": `${otherChar} did not do what was asked of them`,
          "Expectations And Ability": `${otherChar} did not change`,
          "Losing Security, Stability, Trust": `${otherChar} does not feel better`,
      },
      name: "Dysfunctional Relationship",
      selected: false,
    },
    {
      id: '2',
      data: {
          "Respect and Authority": `${mainChar} is losing respect`,
          "Losing Security, Stability, Trust": `${mainChar} does not feel better`,
          "Figuring Things Out": `${otherChar} is rationalizing the situation `,
          "Conflict": `${otherChar} is not making an effort to strengthen their relationship`,
          "Conflict": `${otherChar} criticized and complained `,
          "Conflict": `${otherChar} blamed and accused `,
          "Conflict": `${otherChar} is being hurtful and disrespectful `,
          "Conflict": `${otherChar} is being manipulative to get what they want `,
          "Conflict": `${otherChar} is pressuring and controlling `,
          "Communication": `${otherChar} did not communicate well `,
          "Expectations and Ability": `${otherChar} set boundaries`,
          "Expectations and Ability": `${otherChar} punished ${mainChar}`,
          "Expectations and Ability": `${otherChar} did not change`,
      },
      name: "Punished and Restricted",
      selected: false,
    },
    {
      id: '3',
      data: {
          "Figuring Things Out": `${mainChar} has not figured it out yet`,
          "Losing Security, Stability, Trust": `${mainChar} does not feel better`,
          "Figuring Things Out": `${otherChar} is rationalizing the situation `,
          "Conflict": `${otherChar} is not making an effort to strengthen their relationship`,
          "Conflict": `${otherChar} is being hurtful and disrespectful `,
          "Communication": `${otherChar} did not communicate well `,
          "Respect and Authority": `${otherChar} is losing respect`,
          "Expectations and Ability": `${otherChar} did not do what was asked of them`,
          "Expectations and Ability": `${otherChar} did not change`,
          "Losing Security, Stability, Trust": `${otherChar} does not feel better`,
      },
      name: "Not Meeting Their Obligations",
      selected: false,
    },
    {
      id: '4',
      data: {
          "Figuring Things Out": `${mainChar} is rationalizing the situation `,
          "Figuring Things Out": `${mainChar} has not figured it out yet`,
          "Respect and Authority": `${mainChar} is losing respect`,
          "Independence and Desire": `${mainChar} is not doing what they want to do `,
          "Expectations and Ability": `${mainChar} did not change`,
          "Losing Security, Stability, Trust": `${mainChar} does not feel better`,
          "Figuring Things Out": `${otherChar} is rationalizing the situation `,
          "Conflict": `${otherChar} is not making an effort to strengthen their relationship`,
          "Expectations and Ability": `${otherChar} did not change`,
          "Losing Security, Stability, Trust": `${otherChar} is doing what they want to do `,
      },
      name: "Can't Do What I Want",
      selected: false,
    },
    {
      id: '5',
      data: {
          "Figuring Things Out": `${mainChar} realized something about the situation`,
          "Figuring Things Out": `${mainChar} figured out what to do`,
          "Conflict": `${mainChar} is not making an effort to strengthen their relationship`,
          "Conflict": `${mainChar} made ${otherChar} feel uncomfortable `,
          "Conflict": `${mainChar} is being hurtful and disrespectful `,
          "Conflict": `${mainChar} is being manipulative to get what they want `,
          "Respect and Authority": `${mainChar} is losing respect`,
          "Independence and Desire": `${mainChar} is doing what they want to do `,
          "Finding Security, Stability, Trust": `${mainChar} feels better`,
          "Losing Security, Stability, Trust": `${otherChar} does not feel better`,
      },
      name: "I'm Being Manipulative",
      selected: false,
    },
]

const ClarityInTheMoment_PursuingHarmony = [
{
    id: '1',
    data: {
          "Figuring Things Out": `${mainChar} is rationalizing the situation `,
          "Harmony": `${mainChar} is making an effort to strengthen their relationship`,
          "Harmony": `${mainChar} cared for and helped ${otherChar}`,
          "Harmony": `${mainChar} is being honest `,
          "Losing Security, Stability, Trust": `${mainChar} does not feel better`,
          "Figuring Things Out": `${otherChar} is rationalizing the situation `,
          "Conflict": `${otherChar} is not making an effort to strengthen their relationship`,
          "Communication": `${otherChar} did not communicate well `,
          "Expectations and Ability": `${otherChar} did not change`,
          "Losing Security, Stability, Trust": `${otherChar} does not feel better`,
    },
    name: "Pushing Me Away",
    selected: false,
  },
  {
    id: '2',
    data: {
          "Figuring Things Out": `${mainChar} realized something about the situation`,
          "Figuring Things Out": `${mainChar} figured out what to do`,
          "Harmony": `${mainChar} is making an effort to strengthen their relationship`,
          "Harmony": `${mainChar} is being honest `,
          "Harmony": `${mainChar} cared for and helped ${otherChar}`,
          "Harmony": `${mainChar} protected ${otherChar}`,
          "Communication": `${mainChar} communicated well `,
          "Expectations and Ability": `${mainChar} encouraged and challenged ${otherChar}`,
          "Harmony": `${otherChar} is making an effort to strengthen their relationship`,
    },
    name: "Being Kind and Caring",
    selected: false,
  },
  {
    id: '3',
    data: {
          "Figuring Things Out": `${mainChar} has not figured it out yet`,
          "Harmony": `${mainChar} is making an effort to strengthen their relationship`,
          "Losing Security, Stability, Trust": `${mainChar} does not feel better`,
          "Figuring Things Out": `${otherChar} is rationalizing the situation `,
          "Conflict": `${otherChar} is not making an effort to strengthen their relationship`,
          "Communication": `${otherChar} did not communicate well `,
          "Respect and Authority": `${otherChar} is losing respect`,
          "Expectations and Ability": `${otherChar} did not change`,
          "Losing Security, Stability, Trust": `${otherChar} is ignoring or preventing the pain`,
          "Losing Security, Stability, Trust": `${otherChar} does not feel better`,
    },
    name: "Help Them Get Better",
    selected: false,
  },
  {
    id: '4',
    data: {
          "Figuring Things Out": `${mainChar} realized something about the situation`,
          "Figuring Things Out": `${mainChar} figured out what to do`,
          "Harmony": `${mainChar} is making an effort to strengthen their relationship`,
          "Communication": `${mainChar} communicated well `,
          "Expectations and Ability": `${mainChar} did what was asked of them`,
          "Independence and Desire": `${mainChar} is doing what they want to do `,
          "Finding Security, Stability, Trust": `${mainChar} feels better`,
          "Independence and Desire": `${otherChar} is doing what they want to do `,
          "Finding Security, Stability, Trust": `${otherChar} feels better`,
    },
    name: "Fulfilling My Obligations",
    selected: false,
  },
  {
    id: '5',
    data: {
          "Figuring Things Out": `${mainChar} realized something about the situation`,
          "Figuring Things Out": `${mainChar} figured out what to do`,
          "Relationship Phases": `${mainChar} stayed in the relationship`,
          "Harmony": `${mainChar} is making an effort to strengthen their relationship`,
          "Harmony": `${mainChar} is being honest `,
          "Harmony": `${mainChar} cared for and helped ${otherChar}`,
          "Communication": `${mainChar} communicated well `,
          "Respect and Authority": `${mainChar} is gaining respect `,
          "Expectations and Ability": `${mainChar} focused on bettering themselves`,
          "Expectations and Ability": `${mainChar} did not give up`,
          "Finding Security, Stability, Trust": `${mainChar} feels better`,
          "Figuring Things Out": `${otherChar} figured out what to do`,
          "Harmony": `${otherChar} is making an effort to strengthen their relationship`,
          "Harmony": `${otherChar} is being honest `,
          "Harmony": `${otherChar} cared for and helped ${mainChar}`,
          "Communication": `${otherChar} communicated well `,
          "Respect and Authority": `${otherChar} is gaining respect `,
    },
    name: "Building A Healthy Relationship",
    selected: false,
  },
]

const ClarityInTheFuture_AddressingConflict = [
{
    id: '1',
    data: {
          "Fit and Compatibility": `${mainChar} does not like who ${otherChar} is`,
          "Fit and Compatibility": `${mainChar} and ${otherChar} do not fit well together`,
          "Fit and Compatibility": `${mainChar} does not understand ${otherChar}'s perspective`,
          "Memories and Influences": `${mainChar} is influenced by bad memories`,
          "Losing Security, Stability, Trust": `${mainChar} does not feel secure`,
          "Losing Security, Stability, Trust": `${mainChar} is not treated fairly`,
          "Losing Security, Stability, Trust": `${mainChar} is stressed and tired`,
          "Losing Security, Stability, Trust": `${mainChar} feels like nothing is changing`,
          "Finding Security, Stability, Trust": `${mainChar} wants to feel more secure`,
          "Figuring Things Out": `${mainChar} is trying to understand the situation`,
          "Figuring Things Out": `${mainChar} is figuring out what to do`,
          "Conflict": `${otherChar} is being hurtful and disrespectful`,
          "Conflict": `${otherChar} is being manipulative to get what they want`,
          "Conflict": `${otherChar} is pressuring and controlling`,
          "Communication": `${otherChar} did not communicate well`,
          "Expectations and Ability": `${otherChar} does not want to change`,
          "Fit and Compatibility": `${otherChar} does not like who ${mainChar} is`,
          "Fit and Compatibility": `${otherChar} does not understand ${mainChar}'s perspective`,
          "Figuring Things Out": `${otherChar} is rationalizing the situation`,
    },
    name: "Hurt and Manipulated",
    selected: false,
  },
  {
    id: '2',
    data: {
          "Harmony": `${mainChar} is making an effort to strengthen their relationship`,
          "Fit and Compatibility": `${mainChar} likes who ${otherChar} is`,
          "Fit and Compatibility": `${mainChar} and ${otherChar} do not fit well together`,
          "Fit and Compatibility": `${mainChar} does not understand ${otherChar}'s perspective`,
          "Memories and Influences": `${mainChar} is influenced by bad memories`,
          "Losing Security, Stability, Trust": `${mainChar} does not feel secure`,
          "Losing Security, Stability, Trust": `${mainChar} is not treated fairly`,
          "Losing Security, Stability, Trust": `${mainChar} is stressed and tired`,
          "Losing Security, Stability, Trust": `${mainChar} feels like nothing is changing`,
          "Finding Security, Stability, Trust": `${mainChar} wants to feel more secure`,
          "Figuring Things Out": `${mainChar} is trying to understand the situation`,
          "Figuring Things Out": `${mainChar} does not know what to do`,
          "Conflict": `${otherChar} is not making an effort to strengthen their relationship`,
          "Expectations and Ability": `${otherChar} does not want to change`,
          "Fit and Compatibility": `${otherChar} likes who ${mainChar} is`,
          "Fit and Compatibility": `${otherChar} does not understand ${mainChar}'s perspective`,
          "Memories and Influences": `${otherChar} is influenced by bad memories`,
          "Figuring Things Out": `${otherChar} is rationalizing the situation`,
    },
    name: "One-Sided Relationship",
    selected: false,
  },
  {
    id: '3',
    data: {
          "Fit and Compatibility": `${mainChar} does not like who ${otherChar} is`,
          "Fit and Compatibility": `${mainChar} and ${otherChar} do not fit well together`,
          "Fit and Compatibility": `${mainChar} does not understand ${otherChar}'s perspective`,
          "Memories and Influences": `${mainChar} is influenced by bad memories`,
          "Losing Security, Stability, Trust": `${mainChar} does not feel secure`,
          "Losing Security, Stability, Trust": `${mainChar} is not treated fairly`,
          "Losing Security, Stability, Trust": `${mainChar} is stressed and tired`,
          "Losing Security, Stability, Trust": `${mainChar} feels like nothing is changing`,
          "Finding Security, Stability, Trust": `${mainChar} wants to feel more secure`,
          "Figuring Things Out": `${mainChar} is trying to understand the situation`,
          "Figuring Things Out": `${mainChar} is figuring out what to do`,
          "Conflict": `${otherChar} is not making an effort to strengthen their relationship`,
          "Communication": `${otherChar} did not communicate well`,
          "Respect and Authority": `${otherChar} does not have or is losing respect`,
          "Expectations and Ability": `${otherChar} does not want to do what is asked of them`,
          "Expectations and Ability": `${otherChar} does not want to change`,
          "Independence and Desire": `${otherChar} is doing what they want to do`,
          "Fit and Compatibility": `${otherChar} does not understand ${mainChar}'s perspective`,
          "Memories and Influences": `${otherChar} is influenced by bad memories`,
          "Figuring Things Out": `${otherChar} is rationalizing the situation`,
    },
    name: "They Won't Do What I Tell Them",
    selected: false,
  },
  {
    id: '4',
    data: {
          "Respect and Authority": `${mainChar} does not have or is losing respect`,
          "Independence and Desire": `${mainChar} is not doing what they want to do`,
          "Resources and Opportunity": `${mainChar} does not have what they need`,
          "Fit and Compatibility": `${mainChar} does not like who ${otherChar} is`,
          "Fit and Compatibility": `${mainChar} and ${otherChar} do not fit well together`,
          "Fit and Compatibility": `${mainChar} does not understand ${otherChar}'s perspective`,
          "Memories and Influences": `${mainChar} is influenced by bad memories`,
          "Losing Security, Stability, Trust": `${mainChar} does not feel secure`,
          "Losing Security, Stability, Trust": `${mainChar} is not treated fairly`,
          "Losing Security, Stability, Trust": `${mainChar} is stressed and tired`,
          "Losing Security, Stability, Trust": `${mainChar} feels like nothing is changing`,
          "Finding Security, Stability, Trust": `${mainChar} wants to feel more secure`,
          "Figuring Things Out": `${mainChar} is trying to understand the situation`,
          "Figuring Things Out": `${mainChar} is figuring out what to do`,
          "Conflict": `${otherChar} criticized and complained`,
          "Conflict": `${otherChar} is being hurtful and disrespectful`,
          "Conflict": `${otherChar} is being manipulative to get what they want`,
          "Conflict": `${otherChar} is pressuring and controlling`,
          "Communication": `${otherChar} did not communicate well`,
          "Expectations and Ability": `${otherChar} does not want to change`,
          "Fit and Compatibility": `${otherChar} does not like who ${mainChar} is`,
          "Fit and Compatibility": `${otherChar} does not understand ${mainChar}'s perspective`,
          "Figuring Things Out": `${otherChar} is rationalizing the situation`,
    },
    name: "Can't Do What I Want",
    selected: false,
  },
  {
    id: '5',
    data: {
          "Conflict": `${mainChar} is not making an effort to strengthen their relationship`,
          "Respect and Authority": `${mainChar} does not have or is losing respect`,
          "Respect and Authority": `${mainChar} wants more respect`,
          "Expectations and Ability": `${mainChar} does not want to change`,
          "Independence and Desire": `${mainChar} is doing what they want to do`,
          "Fit and Compatibility": `${mainChar} and ${otherChar} do not fit well together`,
          "Memories and Influences": `${mainChar} is influenced by bad memories`,
          "Losing Security, Stability, Trust": `${mainChar} does not feel secure`,
          "Losing Security, Stability, Trust": `${mainChar} is stressed and tired`,
          "Losing Security, Stability, Trust": `${mainChar} feels like nothing is changing`,
          "Losing Security, Stability, Trust": `${mainChar} wants to feel more secure`,
          "Figuring Things Out": `${mainChar} is figuring out what to do`,
          "Figuring Things Out": `${mainChar} is rationalizing the situation`,
          "Respect and Authority": `${otherChar} has or is gaining respect`,
          "Respect and Authority": `${otherChar} does not have or is losing respect`,
          "Memories and Influences": `${otherChar} is influenced by bad memories`,
          "Losing Security, Stability, Trust": `${otherChar} does not feel secure`,
          "Losing Security, Stability, Trust": `${otherChar} is stressed and tired`,
          "Finding Security, Stability, Trust": `${otherChar} wants to feel more secure`,
    },
    name: "Want More Respect",
    selected: false,
  },
]

const ClarityInTheFuture_PursuingHarmony = [
{
    id: '1',
    data: {
          "Harmony": `${mainChar} is making an effort to strengthen their relationship`,
          "Respect and Authority": `${mainChar} does not have or is losing respect`,
          "Expectations and Ability": `${mainChar} wants to do what is asked of them`,
          "Expectations and Ability": `${mainChar} wants to better themselves`,
          "Independence and Desire": `${mainChar} is not doing what they want to do`,
          "Fit and Compatibility": `${mainChar} likes who ${otherChar} is`,
          "Fit and Compatibility": `${mainChar} and ${otherChar} fit well together`,
          "Fit and Compatibility": `${mainChar} and ${otherChar} do not fit well together`,
          "Memories and Influences": `${mainChar} is influenced by bad memories`,
          "Memories and Influences": `${mainChar} is influenced by good memories`,
          "Memories and Influences": `${mainChar} is influenced by someone else`,
          "Losing Security, Stability, Trust": `${mainChar} does not feel secure`,
          "Losing Security, Stability, Trust": `${mainChar} is stressed and tired`,
          "Losing Security, Stability, Trust": `${mainChar} feels like nothing is changing`,
          "Losing Security, Stability, Trust": `${mainChar} is afraid to fail`,
          "Losing Security, Stability, Trust": `${mainChar} feels lost and alone`,
          "Finding Security, Stability, Trust": `${mainChar} wants to feel more secure`,
          "Figuring Things Out": `${mainChar} is trying to understand the situation`,
          "Figuring Things Out": `${mainChar} is figuring out what to do`,
          "Figuring Things Out": `${mainChar} is rationalizing the situation`,
          "Figuring Things Out": `${mainChar} does not know what to do`,
          "Fit and Compatibility": `${mainChar} does not like who ${otherChar} is`,
          "Respect and Authority": `${otherChar} has or is gaining respect`,
          "Fit and Compatibility": `${otherChar} likes who ${mainChar} is`,
    },
    name: "Afraid to Disappoint",
    selected: false,
  },
  {
    id: '2',
    data: {
          "Harmony": `${mainChar} is making an effort to strengthen their relationship`,
          "Harmony": `${mainChar} wants to care for and help ${otherChar}`,
          "Fit and Compatibility": `${mainChar} likes who ${otherChar} is`,
          "Memories and Influences": `${otherChar} is influenced by bad memories`,
          "Memories and Influences": `${mainChar} is influenced by bad memories`,
          "Fit and Compatibility": `${mainChar} and ${otherChar} fit well together`,
          "Fit and Compatibility": `${mainChar} does not understand ${otherChar}'s perspective`,
          "Losing Security, Stability, Trust": `${mainChar} does not feel secure`,
          "Losing Security, Stability, Trust": `${mainChar} is stressed and tired`,
          "Losing Security, Stability, Trust": `${mainChar} feels like nothing is changing`,
          "Finding Security, Stability, Trust": `${mainChar} wants to feel more secure`,
          "Figuring Things Out": `${mainChar} is trying to understand the situation`,
          "Communication": `${otherChar} is not communicating`,
          "Fit and Compatibility": `${otherChar} likes who ${mainChar} is`,
          "Losing Security, Stability, Trust": `${otherChar} does not feel secure`,
          "Losing Security, Stability, Trust": `${otherChar} is stressed and tired`,
          "Finding Security, Stability, Trust": `${otherChar} wants to feel more secure`,
    },
    name: "Want to Help, but Not Talking to Me",
    selected: false,
  },
  {
    id: '3',
    data: {
        "Harmony": `${mainChar} wants to protect ${otherChar}`,
        "Expectations and Ability": `${mainChar} wants to do what is asked of them`,
        "Expectations and Ability": `${mainChar} can do this well`,
        "Memories and Influences": `${mainChar} is influenced by bad memories`,
        "Memories and Influences": `${mainChar} is influenced by good memories`,
        "Memories and Influences": `${mainChar} is influenced by someone else`,
        "Fit and Compatibility": `${mainChar} does not like who ${otherChar} is`,
        "Fit and Compatibility": `${mainChar} and ${otherChar} do not fit well together`,
        "Fit and Compatibility": `${mainChar} does not understand ${otherChar}'s perspective`,
        "Losing Security, Stability, Trust": `${mainChar} is stressed and tired`,
        "Losing Security, Stability, Trust": `${mainChar} feels like nothing is changing`,
        "Finding Security, Stability, Trust": `${mainChar} wants to feel more secure`,
        "Figuring Things Out": `${mainChar} is trying to understand the situation`,
        "Figuring Things Out": `${mainChar} is figuring out what to do`,
        "Conflict": `${otherChar} is not making an effort to strengthen their relationship`,
        "Communication": `${otherChar} did not communicate well`,
        "Respect and Authority": `${otherChar} does not have or is losing respect`,
        "Expectations and Ability": `${otherChar} cannot do this well`,
        "Expectations and Ability": `${otherChar} does not want to change`,
        "Independence and Desire": `${otherChar} is doing what they want to do`,
        "Memories and Influences": `${otherChar} is influenced by bad memories`,
        "Memories and Influences": `${otherChar} is influenced by someone else`,
        "Fit and Compatibility": `${otherChar} does not understand ${mainChar}'s perspective`,
        "Losing Security, Stability, Trust": `${otherChar} does not feel secure`,
        "Losing Security, Stability, Trust": `${otherChar} is stressed and tired`,
        "Finding Security, Stability, Trust": `${otherChar} wants to feel more secure`,
        "Figuring Things Out": `${otherChar} is rationalizing the situation`,
    },
    name: "Protecting Them Because They Can't",
    selected: false,
  },
  {
    id: '4',
    data: {
        "Harmony": `${mainChar} is making an effort to strengthen their relationship`,
        "Expectations and Ability": `${mainChar} wants to better themselves`,
        "Memories and Influences": `${mainChar} is influenced by bad memories`,
        "Memories and Influences": `${mainChar} is influenced by someone else`,
        "Fit and Compatibility": `${mainChar} likes who ${otherChar} is`,
        "Fit and Compatibility": `${mainChar} and ${otherChar} fit well together`,
        "Losing Security, Stability, Trust": `${mainChar} does not feel secure`,
        "Losing Security, Stability, Trust": `${mainChar} is stressed and tired`,
        "Losing Security, Stability, Trust": `${mainChar} feels like nothing is changing`,
        "Finding Security, Stability, Trust": `${mainChar} wants to feel more secure`,
        "Finding Security, Stability, Trust": `${mainChar} is healing and recovering`,
        "Figuring Things Out": `${mainChar} is trying to understand the situation`,
        "Memories and Influences": `${otherChar} is influenced by bad memories`,
        "Fit and Compatibility": `${otherChar} likes who ${mainChar} is`,
        "Fit and Compatibility": `${otherChar} does not understand ${mainChar}'s perspective`,
        "Finding Security, Stability, Trust": `${otherChar} wants to feel more secure`,
    },
    name: "Trying to Heal the Relationship",
    selected: false,
  },
  {
    id: '5',
    data: {
        "Respect and Authority": `${mainChar} does not have or is losing respect`,
        "Expectations and Ability": `${mainChar} wants to do what is asked of them`,
        "Independence and Desire": `${mainChar} is not doing what they want to do`,
        "Resources and Opportunity": `${mainChar} does not have what they need`,
        "Memories and Influences": `${mainChar} is influenced by bad memories`,
        "Memories and Influences": `${mainChar} is influenced by good memories`,
        "Fit and Compatibility": `${mainChar} does not like who ${otherChar} is`,
        "Fit and Compatibility": `${mainChar} and ${otherChar} do not fit well together`,
        "Fit and Compatibility": `${mainChar} does not understand ${otherChar}'s perspective`,
        "Losing Security, Stability, Trust": `${mainChar} does not feel secure`,
        "Losing Security, Stability, Trust": `${mainChar} is not treated fairly`,
        "Losing Security, Stability, Trust": `${mainChar} is stressed and tired`,
        "Losing Security, Stability, Trust": `${mainChar} feels like nothing is changing`,
        "Finding Security, Stability, Trust": `${mainChar} wants to feel more secure`,
        "Figuring Things Out": `${mainChar} is figuring out what to do`,
        "Figuring Things Out": `${mainChar} does not know what to do`,
        "Communication": `${otherChar} did not communicate well`,
        "Expectations and Ability": `${otherChar} does not want to change`,
        "Fit and Compatibility": `${otherChar} does not understand ${mainChar}'s perspective`,
        "Memories and Influences": `${otherChar} is influenced by bad memories`,
        "Memories and Influences": `${mainChar} is influenced by someone else`,
        "Losing Security, Stability, Trust": `${otherChar} is stressed and tired`,
        "Figuring Things Out": `${otherChar} is rationalizing the situation`,
    },
    name: "Balancing Obligations and My Independence",
    selected: false,
  },
]