import React from 'react'
import { ScrollView, View, Text, SafeAreaView, StyleSheet, TouchableOpacity } from 'react-native'
import BackButtonHeader from '../../components/BackButtonHeader';
import Ionicons from 'react-native-vector-icons/Ionicons';
import BackButton from '../../components/backButton';




const PolicyScreen= ({navigation}) => {
    return (
        <SafeAreaView style={styles.AboutScreen}>
             
         <View style={{
            width: '95%',
            marginLeft: '2.5%',
            top: '5%',
            flexDirection: 'row',
            alignItems: 'center',
          }}>
        <BackButton
          label={'back button'}
          onPress={() => {navigation.navigate('AboutScreen');}}
          icon={<Ionicons name="chevron-back-outline" size={24} color="#18163A" />}
        />

      </View>
    
        <ScrollView style={{top: '5%', marginHorizontal: '5%',}}>
        <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '400', fontSize: 24,  color: '#18163A', marginTop:'10%'}}>
                     NARALYTICS PRIVACY POLICY
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '5%'}}>
                      Naralytics (the “Company”) is committed to maintaining robust privacy protections for its users.  Our Privacy Policy (“Privacy Policy”) is designed to help you understand how we collect, use and safeguard the information you provide to us and to assist you in making informed decisions when using our Service.
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '2%'}}>
                      For purposes of this Agreement, “App” refers to the Company’s mobile application, nara, which can be downloaded via the Apple App Store or Google Play Store.
“Service” refers to the Company’s services accessed via the App. 
The terms “we,” “us,” and “our” refer to the Company, which is Naralytics, Inc.
“You” means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
By accessing our Service, you accept our Privacy Policy and Terms of Use and you consent to our collection, storage, use and disclosure of your Personal Information as described in this Privacy Policy.

                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '400', fontSize: 20,  color: '#18163A', marginTop: '5%'}}>
                      I. INFORMATION WE COLLECT
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '2%'}}>
                      We collect “Non-Personal Information” and “Personal Information.” Non-Personal Information includes information that cannot be used to personally identify you, such as anonymous usage data, general demographic information we may collect, platform types, preferences you submit and preferences that are generated based on the data you submit and number of clicks. Personal Information includes your email and date of birth which you submit to us through the registration process in our app.
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '2%'}}>
                      1. Information collected via Technology
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '2%'}}>
                      To activate the Service you do not need to submit any Personal Information other than your email address and date of birth. To use the Service thereafter, you do not need to submit further Personal Information. However, in an effort to improve the quality of the Service, we track information provided to us by you when you use the Service, such the device from which you connected to the Service, the time and date of access, and other information that does not personally identify you. 
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '2%'}}>
                      2. Information you provide us by registering for an account
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '2%'}}>
                      In addition to the information provided automatically by the App when you visit the Service, to become a subscriber to the Service you will need to create a personal profile. You can create a profile by registering with the Service and entering your email address and date of birth, and creating a user name and a password. By registering, you are authorizing us to collect, store and use your email address and date of birth in accordance with this Privacy Policy.
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '2%'}}>
                      3. Children’s Privacy
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '2%'}}>
                      The Service are not directed to anyone under the age of 13. The Service does not knowingly collect or solicit information from anyone under the age of 13, or allow anyone under the age of 13 to sign up for the Service. In the event that we learn that we have gathered personal information from anyone under the age of 13 without the consent of a parent or guardian, we will delete that information as soon as possible. If you believe we have collected such information, please contact us at www.naralytics.com.
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '400', fontSize: 20,  color: '#18163A', marginTop: '5%'}}>
                      II. HOW WE USE AND SHARE INFORMATION
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '5%'}}>
                      Personal Information
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '2%'}}>
                      Except as otherwise stated in this Privacy Policy, we do not sell, trade, rent or otherwise share for marketing purposes your Personal Information with third parties without your consent. We do share Personal Information with vendors who are performing services for the Company, such as the servers for our email communications who are provided access to user’s email address for purposes of sending emails from us. Those vendors use your Personal Information only at our direction and in accordance with our Privacy Policy.
In general, the Personal Information you provide to us is used to help us communicate with you. For example, we use Personal Information to contact users in response to questions, solicit feedback from users, provide technical support, and inform users about promotional offers.

                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '2%'}}>
                      We may share Personal Information with outside parties if we have a good-faith belief that access, use, preservation or disclosure of the information is reasonably necessary to meet any applicable legal process or enforceable governmental request; to enforce applicable Terms of Service, including investigation of potential violations; address fraud, security or technical concerns; or to protect against harm to the rights, property, or safety of our users or the public as required or permitted by law. 
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '5%'}}>
                      Non-Personal Information
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '2%'}}>
                      In general, we use Non-Personal Information to help us improve the Service and customize the user experience. We also aggregate Non-Personal Information in order to track trends and analyze use patterns on the Site. This Privacy Policy does not limit in any way our use or disclosure of Non-Personal Information and we reserve the right to use and disclose such Non-Personal Information to our partners, advertisers and other third parties at our discretion.
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '2%'}}>
                      In the event we undergo a business transaction such as a merger, acquisition by another company, or sale of all or a portion of our assets, your Personal Information may be among the assets transferred. You acknowledge and consent that such transfers may occur and are permitted by this Privacy Policy, and that any acquirer of our assets may continue to process your Personal Information as set forth in this Privacy Policy. If our information practices change at any time in the future, we will post the policy changes to the App so that you may opt out of the new information practices. We suggest that you check the App periodically if you are concerned about how your information is used.
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '400', fontSize: 20,  color: '#18163A', marginTop: '5%'}}>
                      III. HOW WE PROTECT INFORMATION
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '2%'}}>
                      We implement security measures designed to protect your information from unauthorized access. Your account is protected by your account password and we urge you to take steps to keep your personal information safe by not disclosing your password and by logging out of your account after each use. We further protect your information from potential security breaches by implementing certain technological security measures including encryption, firewalls and secure socket layer technology. However, these measures do not guarantee that your information will not be accessed, disclosed, altered or destroyed by breach of such firewalls and secure server software. By using our Service, you acknowledge that you understand and agree to assume these risks.
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '400', fontSize: 20,  color: '#18163A', marginTop: '5%'}}>
                      IV. TRANSFER OF YOUR PERSONAL DATA
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '2%'}}>
                      Your Personal and Non-Personal information is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction. Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer. 
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '400', fontSize: 20,  color: '#18163A', marginTop: '5%'}}>
                      V. YOUR RIGHTS REGARDING THE USE OF YOUR PERSONAL INFORMATION
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '2%'}}>
                      You have the right at any time to prevent us from contacting you for marketing purposes.  When we send a promotional communication to a user, the user can opt out of further promotional communications by following the unsubscribe instructions provided in each promotional e-mail. Please note that notwithstanding the promotional preferences you indicate by either unsubscribing, we may continue to send you administrative emails including, for example, periodic updates to our Privacy Policy.
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '400', fontSize: 20,  color: '#18163A', marginTop: '5%'}}>
                      VI. LINKS TO OTHER WEBSITES OR APPLICATIONS
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '2%'}}>
                      As part of the Service, we may provide links to or compatibility with other websites or applications. However, we are not responsible for the privacy practices employed by those websites or the information or content they contain. This Privacy Policy applies solely to information collected by us through the Service. Therefore, this Privacy Policy does not apply to your use of a third party website or application accessed by selecting a link on our Service. To the extent that you access or use the Service through or on another website or application, then the privacy policy of that other website or application will apply to your access or use of that site or application. We encourage our users to read the privacy statements of other websites before proceeding to use them.
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '400', fontSize: 20,  color: '#18163A', marginTop: '5%'}}>
                      VII. CHANGES TO OUR PRIVACY POLICY
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '2%'}}>
                      The Company reserves the right to change this policy and our Terms of Service at any time.  We will notify you of significant changes to our Privacy Policy by sending a notice to the primary email address specified in your account or by placing a prominent notice on our site. Significant changes will go into effect 30 days following such notification. Non-material changes or clarifications will take effect immediately. You should periodically check the App and this privacy page for updates.
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '400', fontSize: 20,  color: '#18163A', marginTop: '5%'}}>
                      VIII. CONTACT US
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '2%'}}>
                      If you have any questions regarding this Privacy Policy or the practices of this Site, please contact us through our website at www.naralytics.com.
                      </Text>
                      <Text style={{fontFamily: 'WorkSans-Light', fontWeight: '300', fontSize: 16,  color: '#18163A', marginTop: '2%', marginBottom: '10%'}}>
                      Last Updated: This Privacy Policy was last updated on 5/5/2023.
                      </Text>
            </ScrollView>
        </SafeAreaView>
    )
}

const styles = StyleSheet.create({
    AboutScreen:{
        flex: 1,
        backgroundColor: '#FFF5EF',
    }, 
    BackButtonStyles:{
        position:'relative', 
        top:15, 
        left:-50,  
    }
    
});


export default PolicyScreen;